### ISSUE TITLE
Music lyrics

### ISSUE THREAD

**Issue by GumbewReswolt** [GumbewReswolt/Hello-World#6]

**Comment by MykolaPMP** [comment]
In the End, by Linkin Park

It starts with one thing
I don't know why
It doesn't even matter how hard you try
Keep that in mind
I designed this rhyme
To explain in due time
All I know
Time is a valuable thing
Watch it fly by as the pendulum swings
Watch it count down to the end of the day
The clock ticks life away
It's so unreal
Didn't look out below
Watch the time go right out the window
Trying to hold on, but you didn't even know
Wasted it all just to watch you go
I kept everything inside
And even though I tried, it all fell apart
What it meant to me
Will eventually be a memory of a time when
I tried so hard
And got so far
But in the end
It doesn't even matter
I had to fall
To lose it all
But in the end
It doesn't even matter
One thing, I don't know why
It doesn't even matter how hard you try
Keep that in mind
I designed this rhyme
To remind myself of a time when
I tried so hard
In spite of the way you were mocking me
Acting like I was part of your property
Remembering all the times you fought with me
I'm surprised it got so
Things aren't the way they were before
You wouldn't even recognize me anymore
Not that you knew me back then
But it all comes back to me in the end
You kept everything inside
And even though I tried, it all fell apart
What it meant to me will eventually be a memory of a time when
I tried so hard
And got so far
But in the end
It doesn't even matter
I had to fall
To lose it all
But in the end
It doesn't even matter
I've put my trust in you
Pushed as far as I can go
For all this
There's only one thing you should know
I've put my trust in you
Pushed as far as I can go
For all this
There's only one thing you should know
I tried so hard
And got so far
But in the end
It doesn't even matter
I had to fall
To lose it all
But in the end
It doesn't even matter

Автори пісень: Kat Deluna / Nadir Khayat / Claude Kelly
Текст пісні "In the End", © Warner/Chappell Music, Inc, Universal Music Publishing Group
